language: node_js
node_js:
 - "4"
before_install: curl https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo sh
script: make test-ci
services:
  - redis
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphicsmagick
      - g++-4.8
env:
  - CXX=g++-4.8
