
'use strict';

module.exports = {
  ':mellow:':        'mellow',
  ':o':              'ohmy',
  ';)':              'wink',
  ':P':              'tongue',
  ':D':              'biggrin',
  ':lol:':           'laugh',
  'B)':              'cool',
  ':rolleyes:':      'rolleyes',
  '-_-':             'sleep',
  ':)':              'smile',
  ':wub:':           'wub',
  ':(':              'sad',
  ':unsure:':        'unsure',
  ':wacko:':         'wacko',
  ':blink:':         'blink',
  ':excl:':          'excl',
  ':devil:':         'devil',
  ':innocent:':      'innocent',
  ':bash:':          'bash',
  ':angry:':         'angry',
  ':ninja:':         'ninja',
  ':blush:':         'blush',
  ':bleh:':          'bleh',
  ':coffee:':        'coffee',
  ':megalol:':       'megalol',
  ':haha:':          'haha',
  ':clap:':          'clap',
  ':harhar:':        'harhar',
  ':licklips:':      'licklips',
  ':gun_rifle:':     'gun_rifle',
  ':drinks_cheers:': 'drinks_cheers',
  ':cry:':           'cry',
  ':beer:':          'beer',
  ':thumbsup:':      'thumbsup',
  ':wow:':           'wow',
  ':confused:':      'confused',
  ':?:':             'question'
};
