vbconvert:
  # Base url of the new forum;
  # used for quotes and snippet (topic, post) urls
  destination: 'https://rcopen.com/'

  # Connection details for mysql
  database: 'mysql://root@localhost/vbforum'

  # Usergroup mapping
  #
  # Full syntax:
  #
  #  <mysql_id>:
  #    short_name: <short_name>
  #    parent:     <parent>
  #    settings:
  #      <name>:   { value: true, force: false }
  #
  # Shortcut:
  #
  #  <mysql_id>: <short_name>
  #
  usergroups:
    1:  guests
    2:  incomplete_profile # upgrades to just_registered
    6:  administrators
    7:  moderators
    8:  banned
    10: incomplete_profile # upgrades to novices
    11: incomplete_profile # upgrades to members
    12: violators
    13: che
    14: losers
    30: frozen

  # Permissions for imported moderators assigned to specific sections
  moderator_permissions:
    forum_mod_can_delete_topics:   { value: true }
    forum_mod_can_close_topic:     { value: true }
    forum_mod_can_add_infractions: { value: true }

  # Path to the folder where attachments are stored in
  files: '/tmp/www/uploads/posts'

  # Path to the folder with avatar original pictures ("big" ones)
  avatars: '/tmp/www/custombigprofilepics'

  # Section for abuse reports
  abuse_report_section: 103

  # Market section (disable is_searchable for it and its subsections)
  market_section: 31

  # Usergroup for newly registered users
  registered_user_group: just_registered

  # Original smilies -> markdown-it smilies
  smiley_map:
    ':mellow:':        ':)' # ?
    ':o':              ':o'
    ';)':              ';)'
    ':P':              ':P'
    ':D':              ':grin:'
    ':lol:':           ':laughing:'
    'B)':              'B-)'
    ':rolleyes:':      ':unamused:'
    '-_-':             ':relieved:'
    ':)':              ':)'
    ':wub:':           ':heart_eyes:'
    ':(':              ':('
    ':unsure:':        ':)' # ?
    ':wacko:':         ':dizzy_face:'
    ':blink:':         ':)' # ?
    ':excl:':          ':exclamation:'
    ':devil:':         ':smiling_imp:'
    ':innocent:':      ':innocent:'
    ':bash:':          ':)' # ?
    ':angry:':         ':angry:'
    ':ninja:':         ':)' # ?
    ':blush:':         ':blush:'
    ':bleh:':          ':stuck_out_tongue_closed_eyes:'
    ':coffee:':        ':coffee:'
    ':megalol:':       ':joy:'
    ':haha:':          ':sweat_smile:'
    ':clap:':          ':)' # ?
    ':harhar:':        ':stuck_out_tongue_winking_eye:'
    ':licklips:':      ':yum:'
    ':gun_rifle:':     ':)' # ?
    ':drinks_cheers:': ':)' # ?
    ':cry:':           ':cry:'
    ':beer:':          ':)' # ?
    ':thumbsup:':      ':)' # ?
    ':wow:':           ':astonished:'
    ':confused:':      ':-/'
    ':?:':             ':question:'

  # mapping between vB and nodeca infraction types
  infraction_types:
    5:  frequent_bump
    6:  spam
    7:  multiple_accounts
    8:  warez
    9:  no_price
    10: bad_title
    11: bad_city
    12: duplicate_topic
    13: personal_conversation
    14: wrong_section
    15: bad_profile_image
    16: offtopic
    17: bad_profile_data
    18: overquoting

  # list of domains to force https on (subdomains included)
  force_https:
   - yandex.ru
   - googleusercontent.com
   - mail.ru
   - pp.vk.me
   - hobbyking.com
   - ggpht.com
   - staticflickr.com
   - imgur.com
   - dropbox.com
   - dropboxusercontent.com
   - fbcdn.net
   - akamaihd.net
   - wikimedia.org
   - livefilestore.com
   - yandex.net
   - habrastorage.org
   - google.com
   - avito.st
   - gstatic.com
   - cloudfront.net
   - gyazo.com
   - d-cd.net
   - yadi.sk
   - amazonaws.com
   - wordpress.com
   - twimg.com
   - ytimg.com
   - fotocdn.net
   - tumblr.com
