vbconvert:

  # Connection details for mysql
  #database: 'mysql://username@password:host/database'

  # Usergroup mapping
  usergroups:
    guests: 1
    members: 2
    administrators: 6

  sections:
    hide: [ 42, 102, 114 ]
    ignore: [ 117 ]
