vbconvert:

  # Connection details for mysql
  #database: 'mysql://username@password:host/database'

  # Usergroup mapping
  usergroups:
    guests: 1
    members: 2
    administrators: 6

  # IDs of sections that needs to be hidden or ignored respectively
  sections:
    hide: [ 42, 102, 114 ]
    ignore: [ 117 ]

  # Path to the folder where attachments are stored in
  files: '/tmp/www/uploads/posts'

  # Path to the folder with avatar original pictures ("big" ones)
  avatars: '/tmp/www/custombigprofilepics'
